// SPDX-FileCopyrightText: 2026 Eric Nam
// SPDX-License-Identifier: Apache-2.0

/**
 * @file a3d_font.h
 * @brief A fixed-cell 1-bit font any size, and one blitter for all of them.
 *
 * `a3d_soft_text.h` is 5x7 and nothing else, which is a caption on a 240x320
 * panel and half a millimetre of type on an 800x1280 one. `Canvas::text()`
 * answers that with an integer `scale`, and pixel-doubling a 5x7 gives 3px
 * stems and no weight - a bigger version of a small font, not a bigger font.
 *
 * So: one `Font` describing a cell, one `drawText()` reading it, and the sizes
 * themselves generated by `tools/gen_font.py` into their own headers. A header
 * per size is the point - an 8x16 is 1.5 KB of .rodata and a 20x40 is 11 KB,
 * and a program that wants a caption should pay for neither.
 *
 * ASCII 32..126. See docs/FONTS.md.
 *
 *
 * THE 5x7 IS THE SAME FONT, NOT A SECOND COPY
 * -------------------------------------------
 * `font5x7()` hands the existing hand-authored table back as a `Font`. The
 * table is COLUMN-major and a `Font` is ROW-major, so it is transposed - at
 * compile time, into .rodata, by `_font5x7Rows()`. Re-authoring those 95
 * glyphs in the other layout would have been two tables to keep in step, and
 * a wrong bit in the second one is invisible until somebody reads that letter.
 */

#ifndef A3D_FONT_H_
#define A3D_FONT_H_

#include <stdint.h>
#include <stddef.h>

#include "backends/soft/a3d_soft_text.h"

namespace a3d {

/** A fixed-cell 1-bit font.

    Row-major: `stride` bytes a row, MSB the LEFTMOST pixel, `h` rows a glyph,
    glyph `c` starting at `bits[(c - first) * h * stride]`. `gen_font.py`
    writes exactly this and nothing else reads it.

    `ascent` is the number of rows from the top of the cell down to and
    including the baseline row, so a glyph drawn at baseline `y` puts cell row
    0 at `y - ascent + 1`. For the 5x7 that is 7, which reproduces the
    `y - (kFontH - 1)` that `drawText5x7()` has always used. */
struct Font
    {
    uint8_t w;          ///< cell columns
    uint8_t h;          ///< cell rows
    uint8_t advance;    ///< columns from one glyph origin to the next
    uint8_t ascent;     ///< cell rows at and above the baseline
    uint8_t first;      ///< first character in the table
    uint8_t last;       ///< last character in the table, inclusive
    uint8_t stride;     ///< bytes per row, (w + 7) / 8
    const uint8_t* bits;
    };

/** The rows of one glyph, or of '?' for anything the font does not cover.

    Exposed for the same reason `glyph5x7()` is: a caller drawing into
    something that is not a 16-bit framebuffer - a 1-bit panel, a PNG, a test -
    needs the bits, and the alternative is a second copy of this loop. */
inline const uint8_t* fontGlyph(const Font& f, char ch)
    {
    unsigned c = (unsigned char)ch;
    if ((c < f.first) || (c > f.last)) c = (unsigned)'?';
    if ((c < f.first) || (c > f.last)) c = f.first;   // a font without '?'
    return f.bits + (size_t)(c - f.first) * f.h * f.stride;
    }

/** True if the pixel at (`cx`, `cy`) of this glyph is lit. */
inline bool fontPixel(const Font& f, const uint8_t* glyph, int cx, int cy)
    {
    if ((cx < 0) || (cx >= f.w) || (cy < 0) || (cy >= f.h)) return false;
    return ((glyph[(size_t)cy * f.stride + (cx >> 3)] >> (7 - (cx & 7))) & 1u) != 0u;
    }

/** Width in pixels of `s`, including the advance after the last glyph.

    The trailing advance is deliberate and matches `Canvas::textWidth()` less
    its gap: centring wants the box the text occupies, and a caller that wants
    the ink can subtract `f.advance - f.w`. */
inline int fontTextWidth(const Font& f, const char* s, int scale = 1)
    {
    if ((s == nullptr) || (scale < 1)) return 0;
    int n = 0;
    for (const char* p = s; *p != '\0'; p++) n++;
    return n * f.advance * scale;
    }

/** Draw one line of text into a 16-bit framebuffer.

    `y` is the BASELINE, the same convention as `drawText5x7()`. `scale`
    repeats each glyph pixel as a scale x scale block. Clipping is per pixel,
    so a caption may run off the edge without taking the rest of the line with
    it. */
inline void drawText(uint16_t* fb, int fbStride, int w, int h,
                     int x, int y, const char* s, uint16_t color,
                     const Font& f, int scale = 1)
    {
    if ((fb == nullptr) || (s == nullptr) || (f.bits == nullptr)) return;
    if (scale < 1) return;

    const int top = y - (f.ascent * scale) + scale;
    for (; *s != '\0'; s++, x += f.advance * scale)
        {
        if (x >= w) return;                         // the rest is off the right
        if (x + f.w * scale <= 0) continue;         // ... and this one off the left
        const uint8_t* glyph = fontGlyph(f, *s);
        for (int cy = 0; cy < f.h; cy++)
            {
            const uint8_t* row = glyph + (size_t)cy * f.stride;
            for (int cx = 0; cx < f.w; cx++)
                {
                if (((row[cx >> 3] >> (7 - (cx & 7))) & 1u) == 0u) continue;
                for (int ry = 0; ry < scale; ry++)
                    {
                    const int py = top + cy * scale + ry;
                    if ((py < 0) || (py >= h)) continue;
                    uint16_t* dst = fb + (size_t)py * fbStride;
                    for (int rx = 0; rx < scale; rx++)
                        {
                        const int px = x + cx * scale + rx;
                        if ((px < 0) || (px >= w)) continue;
                        dst[px] = color;
                        }
                    }
                }
            }
        }
    }

/** The 5x7 table transposed from column-major to row-major, at compile time.
    95 glyphs x 7 rows x 1 byte = 665 bytes of .rodata, and no second table to
    keep in step with the first. */
struct _Font5x7Rows { uint8_t b[95 * kFontH]; };

constexpr _Font5x7Rows _font5x7Rows()
    {
    _Font5x7Rows r = {};
    for (int g = 0; g < 95; g++)
        {
        for (int cy = 0; cy < kFontH; cy++)
            {
            uint8_t row = 0;
            for (int cx = 0; cx < kFontW; cx++)
                {
                if (((kFont5x7[g * kFontW + cx] >> cy) & 1u) != 0u)
                    row = (uint8_t)(row | (0x80u >> cx));
                }
            r.b[g * kFontH + cy] = row;
            }
        }
    return r;
    }

inline constexpr _Font5x7Rows kFont5x7Rows = _font5x7Rows();

/** The built-in 5x7 as a `Font`, so a caller can switch sizes by changing one
    reference rather than one function name. */
inline constexpr Font kFont5x7Font = {
    (uint8_t)kFontW,        // w
    (uint8_t)kFontH,        // h
    (uint8_t)kFontAdvance,  // advance
    (uint8_t)kFontH,        // ascent - the cell has no descender
    32,                     // first
    126,                    // last
    1,                      // stride
    kFont5x7Rows.b,
    };

inline const Font& font5x7() { return kFont5x7Font; }

} // namespace a3d

#endif // A3D_FONT_H_
